# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configura la página de GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Sube los archivos desde la carpeta 'demo' (o 'dist')
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './demo'  # Cambia esto si la carpeta es 'dist' u otra

      # Despliega los archivos a GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
